### ISSUE TITLE
Why callback returns value in error even for successful post.

### ISSUE THREAD

**Issue by fizerkhan** [nkohari/node-hipchat#16]
I am calling postMessage, it returns `{status: 'sent'}` in the error of callback. In below, why callback include `value` in error field. It must be `return callback(null, value)`. 

https://github.com/nkohari/node-hipchat/blob/master/lib/hipchat.js#L224-L229

```
              if (res.statusCode === 200) {
                value = options.json === false ? buffer : JSON.parse(buffer);
                return callback(value, null);
              } else {
                return callback(null, buffer);
              }
```

**Comment by dancrumb** [comment]
While you're correct that this breaks node convention, it's been this way since 2012, so we won't be changing the API, since that would break any code that relies on this library
